FILE_POSITIONS = "../../simulations/src/main/resources/positions.txt"
FILE_EXAMPLE = "../../simulations/src/main/resources/example.json"
FILE_CIM_TIMES_VS_N = "../../simulations/src/main/resources/cim_times_vs_n.txt"
FILE_CIM_TIMES_VS_M = "../../simulations/src/main/resources/cim_times_vs_m.txt"
FILE_BFM_TIMES_VS_N = "../../simulations/src/main/resources/bfm_times_vs_n.txt"
FILE_BFM_TIMES_VS_M = "../../simulations/src/main/resources/bfm_times_vs_m.txt"
